#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>

const char *output_file = "../bench_sstr_data.h";
bool g_gen_cpp = false;

static const char* const HEADER = "/*\n * Autogenerated file for tests and benchmarks.\n * Range of the random values: int randomchar = (rand() %% 93) + 33;\n * srand seed used: %d.\n */\n\n";
static const char OPEN[] = "#include <llulu/lu_str.h>\n\nstatic const lu_sstr bench_data[] = {\n    ";
static const char* const ROW = "{\"%s\"}, {\"%s\"}, {\"%s\"}, {\"%s\"}, {\"%s\"}, {\"%s\"}, {\"%s\"}, {\"%s\"}%s";
static const char *const ROW_CONTINUE = ",\n    ";
static const char *const ROW_FINISH = "};\n\n";

static const char OPEN_CPP[] = "#include <string>\n\nstatic const std::string bench_data_s[] = {\n    ";

struct string_pack {
    char s0[32];
    char s1[32];
    char s2[32];
    char s3[32];
    char s4[32];
    char s5[32];
    char s6[32];
    char s7[32];
};

static inline int generate_char(void)
{
    int r = (rand() % 93) + 33;
    while ((r == 37) || (r == 92) || (r == 34)) {
        r = (rand() % 93) + 33;
    }
    return r;
}

void generate_string(char *buf)
{
    int len = rand() % 32;
    for (int i = 0; i < len; ++i) {
        buf[i] = (char)generate_char();
    }
}

void generate_strpack(struct string_pack *strpck)
{
    memset(strpck, 0, sizeof(struct string_pack));
    generate_string(strpck->s0);
    generate_string(strpck->s1);
    generate_string(strpck->s2);
    generate_string(strpck->s3);
    generate_string(strpck->s4);
    generate_string(strpck->s5);
    generate_string(strpck->s6);
    generate_string(strpck->s7);
}

int main(int argc, char **argv)
{
    int seed = 13;
    for (int i = 1; i < argc; ++i) {
        if (argv[i][0] != '-') {
            output_file = argv[i];
            continue;
        }

        switch (argv[i][1]) {
            case 's': seed = atoi(&argv[i][2]);break;
            case 'c': if ('p' == argv[i][2] && argv[i][3] == 'p') {g_gen_cpp = true;} break;
        }
    }

    if (argc == 2) {
        seed = atoi(argv[1]);
    }
    srand(seed);

    struct string_pack strpack;
    char buffer[2048] = {0};

    FILE *f = fopen(output_file, "w");
    if (!f) {
        printf("Cannot open %s for write.\n", output_file);
        return 1;
    }

    int sz = sprintf(buffer, HEADER, seed);
    fwrite(buffer, sz, 1, f);
    fwrite(OPEN, sizeof(OPEN) - 1, 1, f);

    /*  ROW 1  */
    generate_strpack(&strpack);
    memset(buffer, 0, 2048);
    sz = sprintf(buffer, ROW, strpack.s0, strpack.s1, strpack.s2, strpack.s3, strpack.s4, strpack.s5, strpack.s6, strpack.s7, ROW_CONTINUE);
    fwrite(buffer, sz, 1, f);

    /*  ROW 1  */
    generate_strpack(&strpack);
    memset(buffer, 0, 2048);
    sz = sprintf(buffer, ROW, strpack.s0, strpack.s1, strpack.s2, strpack.s3, strpack.s4, strpack.s5, strpack.s6, strpack.s7, ROW_FINISH);
    fwrite(buffer, sz, 1, f);
    

    /* STL String */
    memset(buffer, 0, 2048);
    sz = sprintf(buffer, HEADER, seed);
    fwrite(buffer, sz, 1, f);
    fwrite(OPEN_CPP, sizeof(OPEN_CPP) - 1, 1, f);

    /*  ROW 1  */
    generate_strpack(&strpack);
    memset(buffer, 0, 2048);
    sz = sprintf(buffer, ROW, strpack.s0, strpack.s1, strpack.s2, strpack.s3, strpack.s4, strpack.s5, strpack.s6, strpack.s7, ROW_CONTINUE);
    fwrite(buffer, sz, 1, f);

    /*  ROW 1  */
    generate_strpack(&strpack);
    memset(buffer, 0, 2048);
    sz = sprintf(buffer, ROW, strpack.s0, strpack.s1, strpack.s2, strpack.s3, strpack.s4, strpack.s5, strpack.s6, strpack.s7, ROW_FINISH);
    fwrite(buffer, sz, 1, f);
    fclose(f);
    printf("File %s generated.\n", output_file);

    return 0;
}

