name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  ACT: 'false'  # Cambia a 'true' para pruebas locales

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Dependencies
        run: |
          sudo apt update
          sudo apt install -y valgrind linux-tools-generic libpapi-dev cmake

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --parallel

      - name: Run unit tests
        run: ctest --test-dir build --output-on-failure

      - name: Valgrind Memcheck
        run: ctest --test-dir build -T memcheck

      - name: Run Valgrind Cachegrind
        run: valgrind --tool=cachegrind --cachegrind-out-file=cachegrind.out build/test/mat4_test

      - name: Run Valgrind Callgrind
        run: valgrind --tool=callgrind --callgrind-out-file=callgrind.out build/test/mat4_test

      - name: Run Valgrind Massif
        run: valgrind --tool=massif --massif-out-file=massif.out build/test/mat4_test

      - name: Run Valgrind Helgrind
        run: valgrind --tool=helgrind --log-file=helgrind.out build/test/mat4_test

      - name: Save Valgrind artifacts locally
        if: ${{ env.ACT == 'true' }}
        run: |
          mkdir -p artifacts-local
          mv cachegrind.out artifacts-local/
          mv callgrind.out artifacts-local/
          mv massif.out artifacts-local/
          mv helgrind.out artifacts-local/

      - name: Upload Cachegrind artifact
        if: ${{ env.ACT != 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: cachegrind-profile
          path: cachegrind.out

      - name: Upload Callgrind artifact
        if: ${{ env.ACT != 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: callgrind-profile
          path: callgrind.out

      - name: Upload Massif artifact
        if: ${{ env.ACT != 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: massif-profile
          path: massif.out

      - name: Upload Helgrind artifact
        if: ${{ env.ACT != 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: helgrind-profile
          path: helgrind.out

      - name: Run perf stat
        run: |
          perf stat -e cycles,instructions,cache-references,cache-misses,branch-instructions,branch-misses ./build/test/mat4_test 2> perf_stat.txt || true


      - name: Upload perf stat results
        if: ${{ env.ACT != 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: perf-stat
          path: perf_stat.txt

      - name: Save perf stat locally
        if: ${{ env.ACT == 'true' }}
        run: |
          mkdir -p artifacts-local
          mv perf_stat.txt artifacts-local/


